Feature/des 123
Reprivata-Dev/bootstrap pull request #5
Opened 2021-04-13 19:41 UTC by suejpark00

Updated accordion styles:

![Screen Shot 2021-04-13 at 2 34 11 PM](https://user-images.githubusercontent.com/63370064/114611112-48fbf080-9c66-11eb-8cbe-4cb1cf087ffa.png)

2021-04-14 16:28 UTC, fgutierrezRPVT approved these changes

2021-04-16 04:06 UTC, aarondancer commented on scss/_accordion.scss
> +    // box-shadow: inset 0 ($accordion-border-width * -1) 0 $accordion-border-color;
I think this is for a11y. Might want to keep it or show enough visual contrast some other way to indicate section is active.

2021-04-16 04:06 UTC, aarondancer commented on scss/_accordion.scss
> +      // background-image: escape-svg($accordion-button-active-icon);
Delete dead code

2021-04-16 04:07 UTC, aarondancer requested changes
See comments

2021-04-21 14:25 UTC, merged